// =============================================================================
// Upsync queue — local -> server, FIFO by local timestamp, idempotent
// (03 S5.1 / S5.5.6).
//
// "File d'up-sync par ordre d'horodatage local" (03 S5.1.2): every local
// mutation carries a `localMutationId` (ULID, chronological — 03 S5.5.6,
// generated by `packages/data` at immediate local apply, 03 S5.1.1). The
// queue is the upsync dedup key: repeated re-syncs after multiple outages
// do NOT double-upstream the same mutation (03 S5.5.6). The server dedups
// by `localMutationId` + `idempotency_key` (AD-8: persisted, idempotent,
// retryable, observable).
//
// "offline to online" (03 S5.5): mutations accumulate while offline; on
// reconnect the FULL queue is upstreamed in batches, oldest first (FIFO),
// deduplicated, and conflicts resolved server-wins (scalars) / CRDT
// merge (lists). Bounded batches — never one giant request (03 S5.5.5).
// =============================================================================

import { UlidGenerator } from './ulid';

/** One queued local mutation awaiting upstream. */
export interface UpsyncEntry {
  /** ULID — dedup key (03 S5.5.6), chronological (FIFO by string sort). */
  localMutationId: string;
  /** target mirror table (single module owner, 03 S4.2) */
  entity: string;
  /** row id */
  id: string;
  /** owner module that applies the mutation (single-writer, 03 S4.2) */
  ownerModule: string;
  /** partial payload (03 S3.1: partial intents, never full entities) */
  patch: Record<string, unknown>;
  /** is this a delete? (03 S5.2 downstream delete) */
  isDelete?: boolean;
  /** local apply time (FIFO order, 03 S5.1.2) — NOT the canonical ts */
  localAppliedAtMs: number;
  /** upsync attempt counter (bounded retry, AD-5) */
  attempts: number;
  /** whether the server has acknowledged it (dedup on re-sync) */
  acked?: boolean;
}

export interface BatchOptions {
  /** max mutations per upstream request (03 S5.5.5: bounded, not one giant
   *  request — default 500; the 5000-queue / 24h threshold config is wave-0
   *  data, not hardcoded here, AD-16a). */
  size?: number;
}

/**
 * The upsync queue. FIFO by `localMutationId` (ULID = chronological),
 * idempotent (acked entries are skipped, not re-sent), and lossless:
 * an entry is only removed on server acknowledgement (03 S6: the queue
 * persists on failure — a failed upsync never drops a local mutation).
 */
export class UpsyncQueue {
  private readonly entries = new Map<string, UpsyncEntry>();
  private readonly ulids: UlidGenerator;

  constructor(ulids: UlidGenerator = new UlidGenerator()) {
    this.ulids = ulids;
  }

  /**
   * Enqueue a mutation (03 S5.1.1: applied locally immediately, then
   * queued). Idempotent: enqueuing the same logical mutation twice
   * (same entity+id+patch) yields one entry (AD-8).
   *
   * @returns the assigned `localMutationId` (ULID).
   */
  enqueue(
    entity: string,
    id: string,
    ownerModule: string,
    patch: Record<string, unknown>,
    isDelete = false,
    localAppliedAtMs: number = Date.now(),
  ): string {
    const localMutationId = this.ulids.next();
    const dedupKey = this.dedupKey(entity, id, patch, isDelete);
    const existing = this.findAckedOrQueued(dedupKey, entity, id);
    if (existing) {
      // idempotent: an identical mutation already queued/acked — do not
      // double-enqueue (03 S5.5.6, AD-8).
      return existing.localMutationId;
    }
    this.entries.set(localMutationId, {
      localMutationId,
      entity,
      id,
      ownerModule,
      patch,
      isDelete,
      localAppliedAtMs,
      attempts: 0,
    });
    return localMutationId;
  }

  /** FIFO batch (03 S5.1.2, 03 S5.5.2: oldest first on reconnect). */
  nextBatch(size = 500): UpsyncEntry[] {
    const pending = this.pending();
    return pending.slice(0, size);
  }

  /** All pending (not yet acked) entries, FIFO by ULID. */
  pending(): UpsyncEntry[] {
    return [...this.entries.values()]
      .filter((e) => !e.acked)
      .sort((a, b) => (a.localMutationId < b.localMutationId ? -1 : 1));
  }

  /**
   * Acknowledge a batch from the server (03 S5.1.3 dedup: a mutation
   * already acknowledged upstream is not re-applied — idempotence, AD-8).
   */
  ack(localMutationIds: string[]): void {
    for (const id of localMutationIds) {
      const e = this.entries.get(id);
      if (e) e.acked = true;
    }
  }

  /** Bounded-retry bookkeeping (AD-5: retry transient, no quota bypass). */
  recordAttempt(localMutationIds: string[]): void {
    for (const id of localMutationIds) {
      const e = this.entries.get(id);
      if (e) e.attempts += 1;
    }
  }

  /** Prune server-acked entries (keeps the queue from growing unbounded). */
  pruneAcked(): number {
    let n = 0;
    for (const [k, e] of this.entries) {
      if (e.acked) {
        this.entries.delete(k);
        n++;
      }
    }
    return n;
  }

  size(): number {
    return this.pending().length;
  }

  isEmpty(): boolean {
    return this.size() === 0;
  }

  peekMaxAttempts(): number {
    let max = 0;
    for (const e of this.entries.values()) max = Math.max(max, e.attempts);
    return max;
  }

  private dedupKey(
    entity: string,
    id: string,
    patch: Record<string, unknown>,
    isDelete: boolean,
  ): string {
    return `${entity}|${id}|${isDelete ? 'del' : 'up'}|${stableStringify(patch)}`;
  }

  private findAckedOrQueued(
    dedupKey: string,
    entity: string,
    id: string,
  ): UpsyncEntry | undefined {
    // An acked entry = the mutation already reached the server: a re-queue
    // would be a no-op (dedup, 03 S5.5.6). A pending identical entry =
    // collapse to it (idempotent local apply).
    for (const e of this.entries.values()) {
      if (
        e.entity === entity &&
        e.id === id &&
        e.acked &&
        this.dedupKey(e.entity, e.id, e.patch, !!e.isDelete) === dedupKey
      ) {
        return e;
      }
      if (!e.acked && this.dedupKey(e.entity, e.id, e.patch, !!e.isDelete) === dedupKey) {
        return e;
      }
    }
    return undefined;
  }
}

/** Deterministic stringify (stable key order) for dedup. */
function stableStringify(obj: Record<string, unknown>): string {
  const keys = Object.keys(obj).sort();
  const parts = keys.map((k) => `${k}:${JSON.stringify(obj[k])}`);
  return `{${parts.join(',')}}`;
}
